version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
